name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python 3.12
        run: |
          uv python install 3.12
          uv python pin 3.12

      - name: Sync dependencies
        run: uv sync

      - name: Lint
        run: uv run ruff check

      - name: Test
        run: uv run pytest